title: "Chris Larkin"
baseURL: "https://chris-larkin.github.io/"
languageCode: "en-us"
theme: "custom-wowchemy-theme"

menu:
  main:
    - identifier: home
      name: Home
      url: "/"
      weight: 1
    - identifier: research
      name: Research
      url: "/research/"
      weight: 2
    - identifier: posts
      name: Posts
      url: "/post/"
      weight: 3
    - identifier: contact
      name: Contact
      url: "/contact/"
      weight: 4

params:
  theme: minimal
  font: native
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us
  # Add other parameters like social links, analytics, etc. below
  # Example:
  # social:
  #   twitter: "your_twitter_handle"
  #   github: "your_github_handle"
  # google_analytics:
  #   id: "UA-XXXXXXX-X"

mediaTypes:
  application/manifest+json:
    suffixes: [webmanifest]
  text/netlify:
    delimiter: ''
    suffixes: ['']

outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
  headers:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  redirects:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true

module:
  hugoVersion:
    min: '0.81.0'
    extended: true
  mounts:
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: content
      target: content
